<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2018
 *
 * Generated from /home/bjoern/workspace/CiviSEPA/xml/schema/CRM/Sepa/SepaMandateLink.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:3010c5f4d3afebfc71a9338d8b422a97)
 */

/**
 * Database access object for the SepaMandateLink entity.
 */
class CRM_Sepa_DAO_SepaMandateLink extends CRM_Core_DAO {

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  static $_tableName = 'civicrm_sdd_entity_mandate';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  static $_log = TRUE;

  /**
   * Unique SepaMandateLink ID
   *
   * @var int unsigned
   */
  public $id;

  /**
   * FK to SepaMandate ID
   *
   * @var int unsigned
   */
  public $mandate_id;

  /**
   * Physical table name for entity being linked, eg civicrm_membership
   *
   * @var string
   */
  public $entity_table;

  /**
   * FK to entity table specified in entity_table column
   *
   * @var int unsigned
   */
  public $entity_id;

  /**
   * Link class, freely defined by client
   *
   * @var string
   */
  public $class;

  /**
   * Is this link still active?
   *
   * @var boolean
   */
  public $is_active;

  /**
   * Link creation date
   *
   * @var datetime
   */
  public $creation_date;

  /**
   * Start date of the link (optional)
   *
   * @var datetime
   */
  public $start_date;

  /**
   * End date of the link (optional)
   *
   * @var datetime
   */
  public $end_date;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_sdd_entity_mandate';
    parent::__construct();
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static ::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'mandate_id', 'civicrm_sdd_mandate', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Dynamic(self::getTableName(), 'entity_id', NULL, 'id', 'entity_table');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'Unique SepaMandateLink ID',
          'required' => TRUE,
          'table_name' => 'civicrm_sdd_entity_mandate',
          'entity' => 'SepaMandateLink',
          'bao' => 'CRM_Sepa_DAO_SepaMandateLink',
          'localizable' => 0,
        ],
        'mandate_id' => [
          'name' => 'mandate_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('SepaMandate ID'),
          'description' => 'FK to SepaMandate ID',
          'table_name' => 'civicrm_sdd_entity_mandate',
          'entity' => 'SepaMandateLink',
          'bao' => 'CRM_Sepa_DAO_SepaMandateLink',
          'localizable' => 0,
        ],
        'entity_table' => [
          'name' => 'entity_table',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Entity Table'),
          'description' => 'Physical table name for entity being linked, eg civicrm_membership',
          'maxlength' => 64,
          'size' => CRM_Utils_Type::BIG,
          'table_name' => 'civicrm_sdd_entity_mandate',
          'entity' => 'SepaMandateLink',
          'bao' => 'CRM_Sepa_DAO_SepaMandateLink',
          'localizable' => 0,
        ],
        'entity_id' => [
          'name' => 'entity_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Entity ID'),
          'description' => 'FK to entity table specified in entity_table column',
          'required' => TRUE,
          'table_name' => 'civicrm_sdd_entity_mandate',
          'entity' => 'SepaMandateLink',
          'bao' => 'CRM_Sepa_DAO_SepaMandateLink',
          'localizable' => 0,
        ],
        'class' => [
          'name' => 'class',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Entity Table'),
          'description' => 'Link class, freely defined by client',
          'maxlength' => 16,
          'size' => CRM_Utils_Type::TWELVE,
          'table_name' => 'civicrm_sdd_entity_mandate',
          'entity' => 'SepaMandateLink',
          'bao' => 'CRM_Sepa_DAO_SepaMandateLink',
          'localizable' => 0,
        ],
        'is_active' => [
          'name' => 'is_active',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'description' => 'Is this link still active?',
          'table_name' => 'civicrm_sdd_entity_mandate',
          'entity' => 'SepaMandateLink',
          'bao' => 'CRM_Sepa_DAO_SepaMandateLink',
          'localizable' => 0,
        ],
        'creation_date' => [
          'name' => 'creation_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => ts('Creation Date'),
          'description' => 'Link creation date',
          'table_name' => 'civicrm_sdd_entity_mandate',
          'entity' => 'SepaMandateLink',
          'bao' => 'CRM_Sepa_DAO_SepaMandateLink',
          'localizable' => 0,
        ],
        'start_date' => [
          'name' => 'start_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => ts('Start Date'),
          'description' => 'Start date of the link (optional)',
          'table_name' => 'civicrm_sdd_entity_mandate',
          'entity' => 'SepaMandateLink',
          'bao' => 'CRM_Sepa_DAO_SepaMandateLink',
          'localizable' => 0,
        ],
        'end_date' => [
          'name' => 'end_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => ts('End Date'),
          'description' => 'End date of the link (optional)',
          'table_name' => 'civicrm_sdd_entity_mandate',
          'entity' => 'SepaMandateLink',
          'bao' => 'CRM_Sepa_DAO_SepaMandateLink',
          'localizable' => 0,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'sdd_entity_mandate', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'sdd_entity_mandate', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'index_entity' => [
        'name' => 'index_entity',
        'field' => [
          0 => 'entity_table',
          1 => 'entity_id',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_sdd_entity_mandate::0::entity_table::entity_id',
      ],
      'class' => [
        'name' => 'class',
        'field' => [
          0 => 'class',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_sdd_entity_mandate::0::class',
      ],
      'is_active' => [
        'name' => 'is_active',
        'field' => [
          0 => 'is_active',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_sdd_entity_mandate::0::is_active',
      ],
      'start_date' => [
        'name' => 'start_date',
        'field' => [
          0 => 'start_date',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_sdd_entity_mandate::0::start_date',
      ],
      'end_date' => [
        'name' => 'end_date',
        'field' => [
          0 => 'end_date',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_sdd_entity_mandate::0::end_date',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
