<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2018
 *
 * Generated from /home/bjoern/workspace/CiviSEPA/xml/schema/CRM/Sepa/TransactionGroup.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:a50647edfba02ff840ef166e8583cd2e)
 */

/**
 * Database access object for the SEPATransactionGroup entity.
 */
class CRM_Sepa_DAO_SEPATransactionGroup extends CRM_Core_DAO {

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  static $_tableName = 'civicrm_sdd_txgroup';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  static $_log = TRUE;

  /**
   * ID
   *
   * @var int unsigned
   */
  public $id;

  /**
   * End-to-end reference for this tx group.
   *
   * @var string
   */
  public $reference;

  /**
   * FRST, RCUR or OOFF
   *
   * @var string
   */
  public $type;

  /**
   * Target collection date
   *
   * @var datetime
   */
  public $collection_date;

  /**
   * Latest submission date
   *
   * @var datetime
   */
  public $latest_submission_date;

  /**
   * When was this item created
   *
   * @var datetime
   */
  public $created_date;

  /**
   * fk sepa group Status options in civicrm_option_values
   *
   * @var int unsigned
   */
  public $status_id;

  /**
   * fk to SDD Creditor Id
   *
   * @var int unsigned
   */
  public $sdd_creditor_id;

  /**
   * fk to SDD File Id
   *
   * @var int unsigned
   */
  public $sdd_file_id;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_sdd_txgroup';
    parent::__construct();
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static ::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'sdd_creditor_id', 'civicrm_sdd_creditor', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'sdd_file_id', 'civicrm_sdd_file', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'ID',
          'required' => TRUE,
          'export' => TRUE,
          'where' => 'civicrm_sdd_txgroup.id',
          'headerPattern' => '',
          'dataPattern' => '',
          'table_name' => 'civicrm_sdd_txgroup',
          'entity' => 'SEPATransactionGroup',
          'bao' => 'CRM_Sepa_DAO_SEPATransactionGroup',
          'localizable' => 0,
        ],
        'reference' => [
          'name' => 'reference',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Reference'),
          'description' => 'End-to-end reference for this tx group.',
          'maxlength' => 64,
          'size' => CRM_Utils_Type::BIG,
          'table_name' => 'civicrm_sdd_txgroup',
          'entity' => 'SEPATransactionGroup',
          'bao' => 'CRM_Sepa_DAO_SEPATransactionGroup',
          'localizable' => 0,
        ],
        'type' => [
          'name' => 'type',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Type'),
          'description' => 'FRST, RCUR or OOFF',
          'maxlength' => 4,
          'size' => CRM_Utils_Type::FOUR,
          'table_name' => 'civicrm_sdd_txgroup',
          'entity' => 'SEPATransactionGroup',
          'bao' => 'CRM_Sepa_DAO_SEPATransactionGroup',
          'localizable' => 0,
        ],
        'collection_date' => [
          'name' => 'collection_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => ts('Collection Date'),
          'description' => 'Target collection date',
          'table_name' => 'civicrm_sdd_txgroup',
          'entity' => 'SEPATransactionGroup',
          'bao' => 'CRM_Sepa_DAO_SEPATransactionGroup',
          'localizable' => 0,
        ],
        'latest_submission_date' => [
          'name' => 'latest_submission_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => ts('Latest Submission Date'),
          'description' => 'Latest submission date',
          'table_name' => 'civicrm_sdd_txgroup',
          'entity' => 'SEPATransactionGroup',
          'bao' => 'CRM_Sepa_DAO_SEPATransactionGroup',
          'localizable' => 0,
        ],
        'created_date' => [
          'name' => 'created_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => ts('Created Date'),
          'description' => 'When was this item created',
          'table_name' => 'civicrm_sdd_txgroup',
          'entity' => 'SEPATransactionGroup',
          'bao' => 'CRM_Sepa_DAO_SEPATransactionGroup',
          'localizable' => 0,
        ],
        'status_id' => [
          'name' => 'status_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'fk sepa group Status options in civicrm_option_values',
          'required' => TRUE,
          'table_name' => 'civicrm_sdd_txgroup',
          'entity' => 'SEPATransactionGroup',
          'bao' => 'CRM_Sepa_DAO_SEPATransactionGroup',
          'localizable' => 0,
        ],
        'sdd_creditor_id' => [
          'name' => 'sdd_creditor_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'fk to SDD Creditor Id',
          'table_name' => 'civicrm_sdd_txgroup',
          'entity' => 'SEPATransactionGroup',
          'bao' => 'CRM_Sepa_DAO_SEPATransactionGroup',
          'localizable' => 0,
        ],
        'sdd_file_id' => [
          'name' => 'sdd_file_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'fk to SDD File Id',
          'table_name' => 'civicrm_sdd_txgroup',
          'entity' => 'SEPATransactionGroup',
          'bao' => 'CRM_Sepa_DAO_SEPATransactionGroup',
          'localizable' => 0,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'sdd_txgroup', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'sdd_txgroup', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'UI_reference' => [
        'name' => 'UI_reference',
        'field' => [
          0 => 'reference',
        ],
        'localizable' => FALSE,
        'unique' => TRUE,
        'sig' => 'civicrm_sdd_txgroup::1::reference',
      ],
      'creditor_id' => [
        'name' => 'creditor_id',
        'field' => [
          0 => 'sdd_creditor_id',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_sdd_txgroup::0::sdd_creditor_id',
      ],
      'file_id' => [
        'name' => 'file_id',
        'field' => [
          0 => 'sdd_file_id',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_sdd_txgroup::0::sdd_file_id',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
