<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2018
 *
 * Generated from /home/bjoern/workspace/CiviSEPA/xml/schema/CRM/Sepa/Creditor.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:28a60a2ac97f4f0f1201f885d26ef474)
 */

/**
 * Database access object for the SEPACreditor entity.
 */
class CRM_Sepa_DAO_SEPACreditor extends CRM_Core_DAO {

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  static $_tableName = 'civicrm_sdd_creditor';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  static $_log = TRUE;

  /**
   * ID
   *
   * @var int unsigned
   */
  public $id;

  /**
   * FK to Contact ID that owns that account
   *
   * @var int unsigned
   */
  public $creditor_id;

  /**
   * Provided by the bank. ISO country code+check digit+ZZZ+country specific identifier
   *
   * @var string
   */
  public $identifier;

  /**
   * by default creditor_id.display_name snapshot at creation
   *
   * @var string
   */
  public $name;

  /**
   * by default creditor_id.address (billing) at creation
   *
   * @var string
   */
  public $address;

  /**
   * Which Country does this address belong to.
   *
   * @var int unsigned
   */
  public $country_id;

  /**
   * Iban of the creditor
   *
   * @var string
   */
  public $iban;

  /**
   * BIC of the creditor
   *
   * @var string
   */
  public $bic;

  /**
   * prefix for mandate identifiers
   *
   * @var string
   */
  public $mandate_prefix;

  /**
   * Payment processor link (to be deprecated)
   *
   * @var int unsigned
   */
  public $payment_processor_id;

  /**
   * Default value
   *
   * @var string
   */
  public $category;

  /**
   * Place this creditor's transaction groups in an XML file tagged with this value.
   *
   * @var string
   */
  public $tag;

  /**
   * If true, new Mandates for this Creditor are set to active directly upon creation; otherwise, they have to be activated explicitly later on.
   *
   * @var boolean
   */
  public $mandate_active;

  /**
   * Variant of the pain.008 format to use when generating SEPA XML files for this creditor. FK to SEPA File Formats in civicrm_option_value.
   *
   * @var int unsigned
   */
  public $sepa_file_format_id;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_sdd_creditor';
    parent::__construct();
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static ::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'creditor_id', 'civicrm_contact', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'country_id', 'civicrm_country', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'payment_processor_id', 'civicrm_payment_processor', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'ID',
          'required' => TRUE,
          'table_name' => 'civicrm_sdd_creditor',
          'entity' => 'SEPACreditor',
          'bao' => 'CRM_Sepa_DAO_SEPACreditor',
          'localizable' => 0,
        ],
        'creditor_id' => [
          'name' => 'creditor_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Creditor Contact ID'),
          'description' => 'FK to Contact ID that owns that account',
          'table_name' => 'civicrm_sdd_creditor',
          'entity' => 'SEPACreditor',
          'bao' => 'CRM_Sepa_DAO_SEPACreditor',
          'localizable' => 0,
        ],
        'identifier' => [
          'name' => 'identifier',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('SEPA Creditor identifier'),
          'description' => 'Provided by the bank. ISO country code+check digit+ZZZ+country specific identifier',
          'maxlength' => 35,
          'size' => CRM_Utils_Type::BIG,
          'table_name' => 'civicrm_sdd_creditor',
          'entity' => 'SEPACreditor',
          'bao' => 'CRM_Sepa_DAO_SEPACreditor',
          'localizable' => 0,
        ],
        'name' => [
          'name' => 'name',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('name of the creditor'),
          'description' => 'by default creditor_id.display_name snapshot at creation',
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'table_name' => 'civicrm_sdd_creditor',
          'entity' => 'SEPACreditor',
          'bao' => 'CRM_Sepa_DAO_SEPACreditor',
          'localizable' => 0,
        ],
        'address' => [
          'name' => 'address',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Address of the creditor'),
          'description' => 'by default creditor_id.address (billing) at creation',
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'table_name' => 'civicrm_sdd_creditor',
          'entity' => 'SEPACreditor',
          'bao' => 'CRM_Sepa_DAO_SEPACreditor',
          'localizable' => 0,
        ],
        'country_id' => [
          'name' => 'country_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Country'),
          'description' => 'Which Country does this address belong to.',
          'table_name' => 'civicrm_sdd_creditor',
          'entity' => 'SEPACreditor',
          'bao' => 'CRM_Sepa_DAO_SEPACreditor',
          'localizable' => 0,
        ],
        'iban' => [
          'name' => 'iban',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Iban'),
          'description' => 'Iban of the creditor',
          'required' => FALSE,
          'maxlength' => 42,
          'size' => CRM_Utils_Type::BIG,
          'table_name' => 'civicrm_sdd_creditor',
          'entity' => 'SEPACreditor',
          'bao' => 'CRM_Sepa_DAO_SEPACreditor',
          'localizable' => 0,
        ],
        'bic' => [
          'name' => 'bic',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Bic'),
          'description' => 'BIC of the creditor',
          'maxlength' => 11,
          'size' => CRM_Utils_Type::TWELVE,
          'table_name' => 'civicrm_sdd_creditor',
          'entity' => 'SEPACreditor',
          'bao' => 'CRM_Sepa_DAO_SEPACreditor',
          'localizable' => 0,
        ],
        'mandate_prefix' => [
          'name' => 'mandate_prefix',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Mandate numering prefix'),
          'description' => 'prefix for mandate identifiers',
          'maxlength' => 4,
          'size' => CRM_Utils_Type::FOUR,
          'table_name' => 'civicrm_sdd_creditor',
          'entity' => 'SEPACreditor',
          'bao' => 'CRM_Sepa_DAO_SEPACreditor',
          'localizable' => 0,
        ],
        'payment_processor_id' => [
          'name' => 'payment_processor_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'Payment processor link (to be deprecated)',
          'table_name' => 'civicrm_sdd_creditor',
          'entity' => 'SEPACreditor',
          'bao' => 'CRM_Sepa_DAO_SEPACreditor',
          'localizable' => 0,
        ],
        'category' => [
          'name' => 'category',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Category purpose of the collection'),
          'description' => 'Default value',
          'maxlength' => 4,
          'size' => CRM_Utils_Type::FOUR,
          'table_name' => 'civicrm_sdd_creditor',
          'entity' => 'SEPACreditor',
          'bao' => 'CRM_Sepa_DAO_SEPACreditor',
          'localizable' => 0,
        ],
        'tag' => [
          'name' => 'tag',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Tag'),
          'description' => 'Place this creditor\'s transaction groups in an XML file tagged with this value.',
          'maxlength' => 64,
          'size' => CRM_Utils_Type::BIG,
          'table_name' => 'civicrm_sdd_creditor',
          'entity' => 'SEPACreditor',
          'bao' => 'CRM_Sepa_DAO_SEPACreditor',
          'localizable' => 0,
        ],
        'mandate_active' => [
          'name' => 'mandate_active',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => ts('Immediately activate new Mandates'),
          'description' => 'If true, new Mandates for this Creditor are set to active directly upon creation; otherwise, they have to be activated explicitly later on.',
          'table_name' => 'civicrm_sdd_creditor',
          'entity' => 'SEPACreditor',
          'bao' => 'CRM_Sepa_DAO_SEPACreditor',
          'localizable' => 0,
        ],
        'sepa_file_format_id' => [
          'name' => 'sepa_file_format_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('SEPA File Format'),
          'description' => 'Variant of the pain.008 format to use when generating SEPA XML files for this creditor. FK to SEPA File Formats in civicrm_option_value.',
          'table_name' => 'civicrm_sdd_creditor',
          'entity' => 'SEPACreditor',
          'bao' => 'CRM_Sepa_DAO_SEPACreditor',
          'localizable' => 0,
          'pseudoconstant' => [
            'optionGroupName' => 'sepa_file_format',
            'optionEditPath' => 'civicrm/admin/options/sepa_file_format',
          ]
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'sdd_creditor', $prefix, [
      '',
    ]);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'sdd_creditor', $prefix, [
      '',
    ]);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
